version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\cppagent_dev
image:
- Visual Studio 2017

configuration:
- Debug
#- Release
platform:
- x86

#environment:
#  matrix:
#  - arch: Win32
#  - arch: #does not work, Release|x64 not a valid target

matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

environment:
  BUILD_DIRECTORY: c:\projects\build

before_build:
- cmd: |-
    git submodule init
    git submodule update
    cd ..
    mkdir build
    cd build
    cmake --version
    cmake ../cppagent_dev -G %generator%

build:
  project: '{BUILD_DIRECTORY}'
  verbosity: minimal
  parallel: true

build_script:
- cmd: |-
    cd %BUILD_DIRECTORY%
    cmake --build . --config Debug --target agent_test -- %MSBUILD_FLAGS%

  
test_script:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%\test
    %BUILD_DIRECTORY%\test\Debug\agent_test.exe

  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - cmake/