version: '{build}'
branches:
  only:
  - master
# clone_folder: c:\projects\cppagent_dev
image:
#- Ubuntu
- Visual Studio 2017

configuration:
- Debug
#- Release

platform:
- x86

#environment:
#  matrix:
#  - arch: Win32
#  - arch: #does not work, Release|x64 not a valid target

matrix:
  fast_finish: true

# skip unsupported combinations
init:
- cmd: |-
    set arch=
    if "%arch%"=="Win64" ( set arch= Win64)
    echo %arch%
    echo %APPVEYOR_BUILD_WORKER_IMAGE%
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    echo %generator%

environment:
  MS_BUILD_DIRECTORY: '{APPVEYOR_BUILD_FOLDER}\build'
  LINUX_BUILD_DIRECTORY: '{APPVEYOR_BUILD_FOLDER}/build'

before_build:
- cmd: |-
    git submodule init
    git submodule update
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
- sh: git submodule init
- sh: git submodule update
- sh: mkdir build
- sh: cd build
- sh: cmake --version
- sh: cmake ..
    

build:
  project: '{APPVEYOR_BUILD_FOLDER}/build'
  verbosity: minimal
  parallel: true

build_script:
- cmd: |-
    cd %MS_BUILD_DIRECTORY%
    cmake --build . --config Debug --target agent_test -- %MSBUILD_FLAGS%
- sh: |-
    cd ${LINUX_BUILD_DIRECTORY}
    cmake --build . --config Debug --target agent_test    

test_script:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%\test
    %MS_BUILD_DIRECTORY%\test\Debug\agent_test.exe
- sh: |-
    cd ${APPVEYOR_BUILD_FOLDER}/test
    ${LINUX_BUILD_DIRECTORY}/test/agent_test

  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - cmake/