version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\cppagent_dev
image:
- Visual Studio 2017

clone_folder: c:\projects\cppagent_dev

configuration:
- Debug
#- Release
platform:
- x86
environment:
  matrix:
  - arch: Win32
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    git submodule init
    git submodule update
    cd ..
    mkdir build
    cd build
    cmake --version
    cmake ../cppagent_dev -G %generator%

build:
  project: c:\projects\build
  verbosity: minimal
  parallel: true

test_script:
- cmd: |-
    cd test
    ..\build\test\Debug\agent_text

  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - cmake/